name: Update Bilibili Ranking

on:
  schedule:
    # 每天的北京时间8点和20点运行（UTC时间为0点和12点）
    - cron: '0 0,12 * * *'
  workflow_dispatch: # 允许手动触发工作流

jobs:
  update-ranking:
    runs-on: ubuntu-latest
    # 添加权限配置，授予写入仓库内容的权限
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas tabulate

      - name: Fetch ranking data and update README
        run: |
          python .github/scripts/update_ranking.py
        continue-on-error: false

      - name: Check if README was updated
        id: check_changes
        run: |
          if [ -f "README.md" ]; then
            echo "README.md exists"
            if git diff --quiet README.md; then
              echo "changes=false" >> $GITHUB_OUTPUT
            else
              echo "changes=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "README.md not found"
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update ranking data: $(date '+%Y-%m-%d %H:%M:%S')"
          git push